service: api
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 8080
    webSocketPort: 8081
    lambdaPort: 8082

functions:
  api:
    handler: lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: get
