service: api
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 8080
    webSocketPort: 8081
    lambdaPort: 8082

functions:
  api:
    handler: src/lambda.handler
    events:
      - http: GET /{proxy+}
      - http: HEAD /{proxy+}
      - http: OPTIONS /{proxy+}
      - http: POST /{proxy+}
      - http: PUT /{proxy+}
      - http: DELETE /{proxy+}

